services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_HOSTNAME
        - POSTGRES_PORT
    env_file:
      - .devcontainer/.env
    ports:
      - "8000:8000"
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .devcontainer/.env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  db:
    driver: local
