// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app/configs"
	"app/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(applicationConfig *configs.ApplicationConfig, dbConfig *configs.DBConfig, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(applicationConfig, logger)
	httpServer := server.NewHTTPServer(applicationConfig, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
